name: Test

on:
  push:
    branches: 
      - master
  pull_request:

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -coverprofile=coverage.out -covermode=atomic -v .

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
